export { DetailsButton } from "./details-button"
export { useDetails } from "./use-details"
export type { DetailsButtonProps } from "./details-button"
export type { UseDetailsConfig } from "./use-details"
export { DETAILS_SHORTCUT_KEY } from "./use-details"